# Python stubs generated by omniidl from boggled.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "boggled"
#
__name__ = "boggled"
_0_boggled = omniORB.openModule("boggled", r"boggled.idl")
_0_boggled__POA = omniORB.openModule("boggled__POA", r"boggled.idl")


# exception InvalidCredentialsException
_0_boggled.InvalidCredentialsException = omniORB.newEmptyClass()
class InvalidCredentialsException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/InvalidCredentialsException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.InvalidCredentialsException = InvalidCredentialsException
_0_boggled._d_InvalidCredentialsException  = (omniORB.tcInternal.tv_except, InvalidCredentialsException, InvalidCredentialsException._NP_RepositoryId, "InvalidCredentialsException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_InvalidCredentialsException = omniORB.tcInternal.createTypeCode(_0_boggled._d_InvalidCredentialsException)
omniORB.registerType(InvalidCredentialsException._NP_RepositoryId, _0_boggled._d_InvalidCredentialsException, _0_boggled._tc_InvalidCredentialsException)
del InvalidCredentialsException

# exception UserNotFoundException
_0_boggled.UserNotFoundException = omniORB.newEmptyClass()
class UserNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/UserNotFoundException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.UserNotFoundException = UserNotFoundException
_0_boggled._d_UserNotFoundException  = (omniORB.tcInternal.tv_except, UserNotFoundException, UserNotFoundException._NP_RepositoryId, "UserNotFoundException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_UserNotFoundException = omniORB.tcInternal.createTypeCode(_0_boggled._d_UserNotFoundException)
omniORB.registerType(UserNotFoundException._NP_RepositoryId, _0_boggled._d_UserNotFoundException, _0_boggled._tc_UserNotFoundException)
del UserNotFoundException

# exception InGameException
_0_boggled.InGameException = omniORB.newEmptyClass()
class InGameException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/InGameException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.InGameException = InGameException
_0_boggled._d_InGameException  = (omniORB.tcInternal.tv_except, InGameException, InGameException._NP_RepositoryId, "InGameException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_InGameException = omniORB.tcInternal.createTypeCode(_0_boggled._d_InGameException)
omniORB.registerType(InGameException._NP_RepositoryId, _0_boggled._d_InGameException, _0_boggled._tc_InGameException)
del InGameException

# exception LeaderboardException
_0_boggled.LeaderboardException = omniORB.newEmptyClass()
class LeaderboardException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/LeaderboardException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.LeaderboardException = LeaderboardException
_0_boggled._d_LeaderboardException  = (omniORB.tcInternal.tv_except, LeaderboardException, LeaderboardException._NP_RepositoryId, "LeaderboardException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_LeaderboardException = omniORB.tcInternal.createTypeCode(_0_boggled._d_LeaderboardException)
omniORB.registerType(LeaderboardException._NP_RepositoryId, _0_boggled._d_LeaderboardException, _0_boggled._tc_LeaderboardException)
del LeaderboardException

# exception LoggedInUserException
_0_boggled.LoggedInUserException = omniORB.newEmptyClass()
class LoggedInUserException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/LoggedInUserException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.LoggedInUserException = LoggedInUserException
_0_boggled._d_LoggedInUserException  = (omniORB.tcInternal.tv_except, LoggedInUserException, LoggedInUserException._NP_RepositoryId, "LoggedInUserException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_LoggedInUserException = omniORB.tcInternal.createTypeCode(_0_boggled._d_LoggedInUserException)
omniORB.registerType(LoggedInUserException._NP_RepositoryId, _0_boggled._d_LoggedInUserException, _0_boggled._tc_LoggedInUserException)
del LoggedInUserException

# exception NotExistingWordException
_0_boggled.NotExistingWordException = omniORB.newEmptyClass()
class NotExistingWordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/NotExistingWordException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.NotExistingWordException = NotExistingWordException
_0_boggled._d_NotExistingWordException  = (omniORB.tcInternal.tv_except, NotExistingWordException, NotExistingWordException._NP_RepositoryId, "NotExistingWordException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_NotExistingWordException = omniORB.tcInternal.createTypeCode(_0_boggled._d_NotExistingWordException)
omniORB.registerType(NotExistingWordException._NP_RepositoryId, _0_boggled._d_NotExistingWordException, _0_boggled._tc_NotExistingWordException)
del NotExistingWordException

# exception GameNotFoundException
_0_boggled.GameNotFoundException = omniORB.newEmptyClass()
class GameNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/GameNotFoundException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.GameNotFoundException = GameNotFoundException
_0_boggled._d_GameNotFoundException  = (omniORB.tcInternal.tv_except, GameNotFoundException, GameNotFoundException._NP_RepositoryId, "GameNotFoundException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_GameNotFoundException = omniORB.tcInternal.createTypeCode(_0_boggled._d_GameNotFoundException)
omniORB.registerType(GameNotFoundException._NP_RepositoryId, _0_boggled._d_GameNotFoundException, _0_boggled._tc_GameNotFoundException)
del GameNotFoundException

# exception NotEnoughPlayersException
_0_boggled.NotEnoughPlayersException = omniORB.newEmptyClass()
class NotEnoughPlayersException (CORBA.UserException):
    _NP_RepositoryId = "IDL:boggled/NotEnoughPlayersException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_boggled.NotEnoughPlayersException = NotEnoughPlayersException
_0_boggled._d_NotEnoughPlayersException  = (omniORB.tcInternal.tv_except, NotEnoughPlayersException, NotEnoughPlayersException._NP_RepositoryId, "NotEnoughPlayersException", "message", (omniORB.tcInternal.tv_string,0))
_0_boggled._tc_NotEnoughPlayersException = omniORB.tcInternal.createTypeCode(_0_boggled._d_NotEnoughPlayersException)
omniORB.registerType(NotEnoughPlayersException._NP_RepositoryId, _0_boggled._d_NotEnoughPlayersException, _0_boggled._tc_NotEnoughPlayersException)
del NotEnoughPlayersException

# struct Player
_0_boggled.Player = omniORB.newEmptyClass()
class Player (omniORB.StructBase):
    _NP_RepositoryId = "IDL:boggled/Player:1.0"

    def __init__(self, playerid, username, highscore, gamesPlayed, gamesWon):
        self.playerid = playerid
        self.username = username
        self.highscore = highscore
        self.gamesPlayed = gamesPlayed
        self.gamesWon = gamesWon

_0_boggled.Player = Player
_0_boggled._d_Player  = (omniORB.tcInternal.tv_struct, Player, Player._NP_RepositoryId, "Player", "playerid", omniORB.tcInternal.tv_long, "username", (omniORB.tcInternal.tv_string,0), "highscore", omniORB.tcInternal.tv_long, "gamesPlayed", omniORB.tcInternal.tv_long, "gamesWon", omniORB.tcInternal.tv_long)
_0_boggled._tc_Player = omniORB.tcInternal.createTypeCode(_0_boggled._d_Player)
omniORB.registerType(Player._NP_RepositoryId, _0_boggled._d_Player, _0_boggled._tc_Player)
del Player

# struct PlayerData
_0_boggled.PlayerData = omniORB.newEmptyClass()
class PlayerData (omniORB.StructBase):
    _NP_RepositoryId = "IDL:boggled/PlayerData:1.0"

    def __init__(self, username, score):
        self.username = username
        self.score = score

_0_boggled.PlayerData = PlayerData
_0_boggled._d_PlayerData  = (omniORB.tcInternal.tv_struct, PlayerData, PlayerData._NP_RepositoryId, "PlayerData", "username", (omniORB.tcInternal.tv_string,0), "score", omniORB.tcInternal.tv_long)
_0_boggled._tc_PlayerData = omniORB.tcInternal.createTypeCode(_0_boggled._d_PlayerData)
omniORB.registerType(PlayerData._NP_RepositoryId, _0_boggled._d_PlayerData, _0_boggled._tc_PlayerData)
del PlayerData

# struct PlayerList
_0_boggled.PlayerList = omniORB.newEmptyClass()
class PlayerList (omniORB.StructBase):
    _NP_RepositoryId = "IDL:boggled/PlayerList:1.0"

    def __init__(self, players):
        self.players = players

_0_boggled.PlayerList = PlayerList
_0_boggled._d_PlayerList  = (omniORB.tcInternal.tv_struct, PlayerList, PlayerList._NP_RepositoryId, "PlayerList", "players", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:boggled/PlayerData:1.0"], 0))
_0_boggled._tc_PlayerList = omniORB.tcInternal.createTypeCode(_0_boggled._d_PlayerList)
omniORB.registerType(PlayerList._NP_RepositoryId, _0_boggled._d_PlayerList, _0_boggled._tc_PlayerList)
del PlayerList

# struct RoundLetters
_0_boggled.RoundLetters = omniORB.newEmptyClass()
class RoundLetters (omniORB.StructBase):
    _NP_RepositoryId = "IDL:boggled/RoundLetters:1.0"

    def __init__(self, letters):
        self.letters = letters

_0_boggled.RoundLetters = RoundLetters
_0_boggled._d_RoundLetters  = (omniORB.tcInternal.tv_struct, RoundLetters, RoundLetters._NP_RepositoryId, "RoundLetters", "letters", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_wchar, 0))
_0_boggled._tc_RoundLetters = omniORB.tcInternal.createTypeCode(_0_boggled._d_RoundLetters)
omniORB.registerType(RoundLetters._NP_RepositoryId, _0_boggled._d_RoundLetters, _0_boggled._tc_RoundLetters)
del RoundLetters

# interface PlayerServices
_0_boggled._d_PlayerServices = (omniORB.tcInternal.tv_objref, "IDL:boggled/PlayerServices:1.0", "PlayerServices")
omniORB.typeMapping["IDL:boggled/PlayerServices:1.0"] = _0_boggled._d_PlayerServices
_0_boggled.PlayerServices = omniORB.newEmptyClass()
class PlayerServices :
    _NP_RepositoryId = _0_boggled._d_PlayerServices[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_boggled.PlayerServices = PlayerServices
_0_boggled._tc_PlayerServices = omniORB.tcInternal.createTypeCode(_0_boggled._d_PlayerServices)
omniORB.registerType(PlayerServices._NP_RepositoryId, _0_boggled._d_PlayerServices, _0_boggled._tc_PlayerServices)

# PlayerServices operations and attributes
PlayerServices._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_boggled.LoggedInUserException._NP_RepositoryId: _0_boggled._d_LoggedInUserException, _0_boggled.UserNotFoundException._NP_RepositoryId: _0_boggled._d_UserNotFoundException, _0_boggled.InvalidCredentialsException._NP_RepositoryId: _0_boggled._d_InvalidCredentialsException})
PlayerServices._d_getCurrentGame = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_waitingLobby = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
PlayerServices._d_getLobbySize = ((), (omniORB.tcInternal.tv_long, ), None)
PlayerServices._d_startGame = ((), (omniORB.tcInternal.tv_long, ), {_0_boggled.NotEnoughPlayersException._NP_RepositoryId: _0_boggled._d_NotEnoughPlayersException})
PlayerServices._d_getPlayers = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.typeMapping["IDL:boggled/PlayerList:1.0"], ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getLetters = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:boggled/RoundLetters:1.0"], ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_submitWords = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_boggled.NotExistingWordException._NP_RepositoryId: _0_boggled._d_NotExistingWordException})
PlayerServices._d_isWordSubmitted = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getRoundWaitingTime = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getRoundNumber = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getRoundTime = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getRoundWinner = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getRoundScore = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getGameWinner = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_getGameScore = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, ), {_0_boggled.GameNotFoundException._NP_RepositoryId: _0_boggled._d_GameNotFoundException})
PlayerServices._d_viewLeaderboard = ((), (omniORB.typeMapping["IDL:boggled/PlayerList:1.0"], ), {_0_boggled.LeaderboardException._NP_RepositoryId: _0_boggled._d_LeaderboardException})
PlayerServices._d_viewProfile = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:boggled/Player:1.0"], ), {_0_boggled.UserNotFoundException._NP_RepositoryId: _0_boggled._d_UserNotFoundException})
PlayerServices._d_logout = ((omniORB.tcInternal.tv_long, ), (), {_0_boggled.InGameException._NP_RepositoryId: _0_boggled._d_InGameException})
PlayerServices._d_updateHighScore = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_boolean, ), None)
PlayerServices._d_getUsernameByID = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), {_0_boggled.UserNotFoundException._NP_RepositoryId: _0_boggled._d_UserNotFoundException})

# PlayerServices object reference
class _objref_PlayerServices (CORBA.Object):
    _NP_RepositoryId = PlayerServices._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_boggled.PlayerServices._d_login, args)

    def getCurrentGame(self, *args):
        return self._obj.invoke("getCurrentGame", _0_boggled.PlayerServices._d_getCurrentGame, args)

    def waitingLobby(self, *args):
        return self._obj.invoke("waitingLobby", _0_boggled.PlayerServices._d_waitingLobby, args)

    def getLobbySize(self, *args):
        return self._obj.invoke("getLobbySize", _0_boggled.PlayerServices._d_getLobbySize, args)

    def startGame(self, *args):
        return self._obj.invoke("startGame", _0_boggled.PlayerServices._d_startGame, args)

    def getPlayers(self, *args):
        return self._obj.invoke("getPlayers", _0_boggled.PlayerServices._d_getPlayers, args)

    def getLetters(self, *args):
        return self._obj.invoke("getLetters", _0_boggled.PlayerServices._d_getLetters, args)

    def submitWords(self, *args):
        return self._obj.invoke("submitWords", _0_boggled.PlayerServices._d_submitWords, args)

    def isWordSubmitted(self, *args):
        return self._obj.invoke("isWordSubmitted", _0_boggled.PlayerServices._d_isWordSubmitted, args)

    def getRoundWaitingTime(self, *args):
        return self._obj.invoke("getRoundWaitingTime", _0_boggled.PlayerServices._d_getRoundWaitingTime, args)

    def getRoundNumber(self, *args):
        return self._obj.invoke("getRoundNumber", _0_boggled.PlayerServices._d_getRoundNumber, args)

    def getRoundTime(self, *args):
        return self._obj.invoke("getRoundTime", _0_boggled.PlayerServices._d_getRoundTime, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_boggled.PlayerServices._d_getRoundWinner, args)

    def getRoundScore(self, *args):
        return self._obj.invoke("getRoundScore", _0_boggled.PlayerServices._d_getRoundScore, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_boggled.PlayerServices._d_getGameWinner, args)

    def getGameScore(self, *args):
        return self._obj.invoke("getGameScore", _0_boggled.PlayerServices._d_getGameScore, args)

    def viewLeaderboard(self, *args):
        return self._obj.invoke("viewLeaderboard", _0_boggled.PlayerServices._d_viewLeaderboard, args)

    def viewProfile(self, *args):
        return self._obj.invoke("viewProfile", _0_boggled.PlayerServices._d_viewProfile, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_boggled.PlayerServices._d_logout, args)

    def updateHighScore(self, *args):
        return self._obj.invoke("updateHighScore", _0_boggled.PlayerServices._d_updateHighScore, args)

    def getUsernameByID(self, *args):
        return self._obj.invoke("getUsernameByID", _0_boggled.PlayerServices._d_getUsernameByID, args)

omniORB.registerObjref(PlayerServices._NP_RepositoryId, _objref_PlayerServices)
_0_boggled._objref_PlayerServices = _objref_PlayerServices
del PlayerServices, _objref_PlayerServices

# PlayerServices skeleton
__name__ = "boggled__POA"
class PlayerServices (PortableServer.Servant):
    _NP_RepositoryId = _0_boggled.PlayerServices._NP_RepositoryId


    _omni_op_d = {"login": _0_boggled.PlayerServices._d_login, "getCurrentGame": _0_boggled.PlayerServices._d_getCurrentGame, "waitingLobby": _0_boggled.PlayerServices._d_waitingLobby, "getLobbySize": _0_boggled.PlayerServices._d_getLobbySize, "startGame": _0_boggled.PlayerServices._d_startGame, "getPlayers": _0_boggled.PlayerServices._d_getPlayers, "getLetters": _0_boggled.PlayerServices._d_getLetters, "submitWords": _0_boggled.PlayerServices._d_submitWords, "isWordSubmitted": _0_boggled.PlayerServices._d_isWordSubmitted, "getRoundWaitingTime": _0_boggled.PlayerServices._d_getRoundWaitingTime, "getRoundNumber": _0_boggled.PlayerServices._d_getRoundNumber, "getRoundTime": _0_boggled.PlayerServices._d_getRoundTime, "getRoundWinner": _0_boggled.PlayerServices._d_getRoundWinner, "getRoundScore": _0_boggled.PlayerServices._d_getRoundScore, "getGameWinner": _0_boggled.PlayerServices._d_getGameWinner, "getGameScore": _0_boggled.PlayerServices._d_getGameScore, "viewLeaderboard": _0_boggled.PlayerServices._d_viewLeaderboard, "viewProfile": _0_boggled.PlayerServices._d_viewProfile, "logout": _0_boggled.PlayerServices._d_logout, "updateHighScore": _0_boggled.PlayerServices._d_updateHighScore, "getUsernameByID": _0_boggled.PlayerServices._d_getUsernameByID}

PlayerServices._omni_skeleton = PlayerServices
_0_boggled__POA.PlayerServices = PlayerServices
omniORB.registerSkeleton(PlayerServices._NP_RepositoryId, PlayerServices)
del PlayerServices
__name__ = "boggled"

#
# End of module "boggled"
#
__name__ = "boggled_idl"

_exported_modules = ( "boggled", )

# The end.
