module boggled {

    exception InvalidCredentialsException {
        string message;
    };
    exception UserNotFoundException {
        string message;
    };
    exception InGameException {
        string message;
    };

    exception LeaderboardException {
        string message;
    };

    exception LoggedInUserException {
        string message;
    };

    exception NotExistingWordException {
        string message;
    };

    exception GameNotFoundException {
        string message;
    };

    exception NotEnoughPlayersException {
        string message;
    };


    struct Player {
        long playerid;
        string username;
        long highscore;
        long gamesPlayed;
        long gamesWon;
    };

    struct PlayerData {
        string username;
        long score;
    };

    struct PlayerList {
        sequence<PlayerData> players;
    };

    struct RoundLetters {
        sequence<wchar> letters;
    };

    interface PlayerServices {
        long login(in string username, in string password) raises (LoggedInUserException, UserNotFoundException, InvalidCredentialsException);
        long waitingLobby(in long playerID);
        long getLobbySize();
        void startGame(in long playerID) raises (NotEnoughPlayersException, GameNotFoundException);
        PlayerList getPlayers(in long playerID, in long roundNum) raises (GameNotFoundException);
        RoundLetters getLetters (in long playerID) raises (GameNotFoundException);
        long submitWords(in long playerID, in string word) raises (NotExistingWordException, GameNotFoundException);
        boolean isWordSubmitted (in long playerID, in string word) raises (GameNotFoundException);
        long getRoundWaitingTime(in long playerID) raises (GameNotFoundException);
        long getRoundTime(in long playerID) raises (GameNotFoundException);
        PlayerData getGameWinner (in long playerID) raises (GameNotFoundException);
        PlayerList viewLeaderboard() raises (LeaderboardException);
        Player viewProfile(in long playerID) raises (UserNotFoundException);
        void logout(in long playerID) raises (InGameException);
    };
};