module boggled {

    exception InvalidCredentialsException {
        string message;
    };
    exception UserNotFoundException {
        string message;
    };
    exception InGameException {
        string message;
    };

    exception LeaderboardException {
        string message;
    };

    exception LoggedInUserException {
        string message;
    };

    exception NotExistingWordException {
        string message;
    };

    exception GameNotFoundException {
        string message;
    };

    exception NotEnoughPlayersException {
        string message;
    };


    struct Player {
        long playerid;
        string username;
        long highscore;
        long gamesPlayed;
        long gamesWon;
    };

    struct PlayerData {
        string username;
        long score;
    };

    struct PlayerList {
        sequence<PlayerData> players;
    };

    struct RoundLetters {
        sequence<wchar> letters;
    };

    interface PlayerServices {
        long login(in string username, in string password) raises (LoggedInUserException, UserNotFoundException, InvalidCredentialsException);
        long getCurrentGame(in long playerid) raises (GameNotFoundException);
        long waitingLobby(in long playerid);
        long getLobbySize();
        long startGame() raises (NotEnoughPlayersException);
        PlayerList getPlayers(in long gameid, in long roundNum) raises (GameNotFoundException);
        RoundLetters getLetters (in long gameid) raises (GameNotFoundException);
        long submitWords(in long playerid, in string word, in long gameid) raises (NotExistingWordException);
        boolean isWordSubmitted (in long gameid, in long playerid, in string word) raises (GameNotFoundException);
        long getRoundWaitingTime(in long gameid) raises (GameNotFoundException);
        long getRoundNumber(in long gameid) raises (GameNotFoundException);
        long getRoundTime(in long gameid) raises (GameNotFoundException);
        long getRoundWinner (in long gameid, in long roundNum) raises (GameNotFoundException);
        long getRoundScore (in long playerid, in long gameid, in long roundNum) raises (GameNotFoundException);
        long getGameWinner (in long gameid) raises (GameNotFoundException);
        long getGameScore (in long gameid, in long playerid) raises (GameNotFoundException);
        PlayerList viewLeaderboard() raises (LeaderboardException);
        Player viewProfile(in long playerid) raises (UserNotFoundException);
        void logout(in long playerid) raises (InGameException);
        boolean updateHighScore(in long playerid, in long newScore);
        string getUsernameByID(in long playerid) raises (UserNotFoundException);
    };
};
