# DO NOT EDIT THIS FILE!
#
# Python module boggled__POA generated by omniidl

import omniORB
omniORB.updateModule("boggled__POA")

# ** 1. Stub files contributing to this module
import boggled_idl

# ** 2. Sub-modules

# ** 3. End
